# input image size and future trajectory time sequence
IMAGE_HEIGHT = 400  # 400, 384
IMAGE_WIDTH = 400  # 400, 384
NUM_CHANNELS = 4
FUTURE_TIME_STEP = 30
PAST_TIME_STEP = 19
SURR_TIME_STEP = 19

# Training
NUM_EPOCHS = 10
STEPS_PER_EPOCH = 2
BATCH_SIZE = 2

# Boost
HARD_SAMPLE_RATIO = 3
NORMAL_TRAIN_EPOCH = 1  # must >= 1
RESERVOIR_MAX_SIZE = BATCH_SIZE * 50

# GMM
NUM_GAUSSIAN_COMPONENT = 6
